services:
  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile.prod
    ports:
      - "3001:3001"
    env_file:
      - ./.env.production
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env.production
    environment:
      - NODE_ENV=production

  db:
    image: postgres:17.5
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: