export enum EnvKey {
  NODE_ENV = 'NODE_ENV',
  BACKEND_PORT = 'BACKEND_PORT',
  FRONTEND_PORT = 'FRONTEND_PORT',
  CORS_ORIGIN = 'CORS_ORIGIN',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DB = 'POSTGRES_DB',
  POSTGRES_PORT = 'POSTGRES_PORT',
  DATABASE_URL = 'DATABASE_URL',
  REDIS_URL = 'REDIS_URL',
  JWT_SECRET = 'JWT_SECRET',
  NEXT_PUBLIC_API_BASE_URL = 'NEXT_PUBLIC_API_BASE_URL',
}
